calendar:
  key: AIzaSyD7A3BcJKsHCB7XEoGxQ5BGIhYhF0P42fA
  1a: 169u8pr5vrf296hmigiehltr8o@group.calendar.google.com
  2a: cmr96jsu22k4qs7mh0akh6u9vc@group.calendar.google.com
  2ao: 0n50q3l187pmjujgooeuq1ajmo@group.calendar.google.com
  2ailc: tuncqd8et6hgjsm2baok6vefpc69kir1@import.calendar.google.com
  2aisi: r52qvo7nfr7n5hdv0gib47motuc2tcn3@import.calendar.google.com
  3a: k9lf59hq805o5enoo01mhjv9m8@group.calendar.google.com
  3ao: ao4pukmvs5gdh0nci38akoc0n8@group.calendar.google.com
  3ailc: ql6794s618ns58qgh56qdehcjnnc7987@import.calendar.google.com
  3aisi: ecpq8mr4fhj2agd10sncsbd13ho74rj2@import.calendar.google.com
  bde: lhonilnm3lvk7o4g1d556pf1hk@group.calendar.google.com
aws:
  access_key_id: AKIAIPVH6UOBL23IZXBA
  secret_access_key: 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
  bucket: ares-intranet-storage
  bucket-profiles: "ares-intranet-profiles"
