calendar:
  key: AIzaSyD7A3BcJKsHCB7XEoGxQ5BGIhYhF0P42fA
  1a: 169u8pr5vrf296hmigiehltr8o@group.calendar.google.com
  2a: cmr96jsu22k4qs7mh0akh6u9vc@group.calendar.google.com
  2ao: 0n50q3l187pmjujgooeuq1ajmo@group.calendar.google.com
  2ailc: cf31n2qun97bf7rkgd88eh3fhleslhg2@import.calendar.google.com
  2aisi: ok0os11jcgjmum7n49p0cf0mpbmdd7qu@import.calendar.google.com
  3a: k9lf59hq805o5enoo01mhjv9m8@group.calendar.google.com
  3ao: ao4pukmvs5gdh0nci38akoc0n8@group.calendar.google.com
  3ailc: 8qmsb3vj2c8u78e1lmft2ac3i2cmevc2@import.calendar.google.com
  3aisi: au0t4s83fn9j3gbbsed6aovv9qpojqos@import.calendar.google.com
  bde: lhonilnm3lvk7o4g1d556pf1hk@group.calendar.google.com
aws:
  access_key_id: AKIAIPVH6UOBL23IZXBA
  secret_access_key: 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
  bucket: ares-intranet-storage
  bucket-profiles: "ares-intranet-profiles"
