calendar:
  key: AIzaSyD7A3BcJKsHCB7XEoGxQ5BGIhYhF0P42fA
  default:
    all:
      - evtsBDE
      - campagne
    2019:
      - cours1A
    2018:
      - cours2A
      - options2A
    2017:
      - cours3A
      - options3A
  groups: !omap
    1A:
      - cours1A
    2A:
      - cours2A
      - options2A
      - ilc2A
      - isi2A
    3A:
      - cours3A
      - options3A
      - ilc3A
      - isi3A
    BDE:
      - evtsBDE
      - campagne
  list:
    cours1A: 
      id: 169u8pr5vrf296hmigiehltr8o@group.calendar.google.com
      text: "Cours"
      color: "#006400"
      public:
        html: "https://www.google.com/calendar/embed?src=169u8pr5vrf296hmigiehltr8o%40group.calendar.google.com&ctz=Europe/Paris"
        ical: "https://calendar.google.com/calendar/ical/169u8pr5vrf296hmigiehltr8o%40group.calendar.google.com/public/basic.ics"
    cours2A: 
      id: cmr96jsu22k4qs7mh0akh6u9vc@group.calendar.google.com
      text: "Cours"
      color: "#ff8000"
      public:
        html: "https://www.google.com/calendar/embed?src=cmr96jsu22k4qs7mh0akh6u9vc%40group.calendar.google.com&ctz=Europe/Paris"
        ical: "https://www.google.com/calendar/ical/cmr96jsu22k4qs7mh0akh6u9vc%40group.calendar.google.com/public/basic.ics"
    options2A: 
      id: 0n50q3l187pmjujgooeuq1ajmo@group.calendar.google.com
      text: "Options"
      color: "#ff0000"
      public:
        html: "https://www.google.com/calendar/embed?src=0n50q3l187pmjujgooeuq1ajmo%40group.calendar.google.com&ctz=Europe/Paris"
        ical: "https://www.google.com/calendar/ical/0n50q3l187pmjujgooeuq1ajmo%40group.calendar.google.com/public/basic.ics"
    ilc2A: 
      id: cf31n2qun97bf7rkgd88eh3fhleslhg2@import.calendar.google.com
      text: "ILC"
      color: "#ff6366"
      public:
        html: "https://www.google.com/calendar/embed?src=cf31n2qun97bf7rkgd88eh3fhleslhg2%40import.calendar.google.com&ctz=Europe/Paris"
        ical: "https://www.google.com/calendar/ical/cf31n2qun97bf7rkgd88eh3fhleslhg2%40import.calendar.google.com/public/basic.ics"
    isi2A: 
      id: ok0os11jcgjmum7n49p0cf0mpbmdd7qu@import.calendar.google.com
      text: "ISI"
      color: "#ff4400"
      public:
        html: "https://www.google.com/calendar/embed?src=ok0os11jcgjmum7n49p0cf0mpbmdd7qu%40import.calendar.google.com&ctz=Europe/Paris"
        ical: "https://www.google.com/calendar/ical/ok0os11jcgjmum7n49p0cf0mpbmdd7qu%40import.calendar.google.com/public/basic.ics"
    cours3A: 
      id: k9lf59hq805o5enoo01mhjv9m8@group.calendar.google.com
      text: "Cours"
      color: "#2872d1"
      public:
        html: "https://www.google.com/calendar/embed?src=k9lf59hq805o5enoo01mhjv9m8%40group.calendar.google.com&ctz=Europe/Paris"
        ical: "https://calendar.google.com/calendar/ical/k9lf59hq805o5enoo01mhjv9m8%40group.calendar.google.com/public/basic.ics"
    options3A: 
      id: ao4pukmvs5gdh0nci38akoc0n8@group.calendar.google.com
      text: "Options"
      color: "#00008b"
      public:
        html: "https://www.google.com/calendar/embed?src=ao4pukmvs5gdh0nci38akoc0n8%40group.calendar.google.com&ctz=Europe/Paris"
        ical: "https://calendar.google.com/calendar/ical/ao4pukmvs5gdh0nci38akoc0n8%40group.calendar.google.com/public/basic.ics"
    ilc3A: 
      id: 8qmsb3vj2c8u78e1lmft2ac3i2cmevc2@import.calendar.google.com
      text: "ILC"
      color: "#79c5de"
      public:
        html: "https://www.google.com/calendar/embed?src=8qmsb3vj2c8u78e1lmft2ac3i2cmevc2%40import.calendar.google.com&ctz=Europe/Paris"
        ical: "https://www.google.com/calendar/ical/8qmsb3vj2c8u78e1lmft2ac3i2cmevc2%40import.calendar.google.com/public/basic.ics"
    isi3A: 
      id: au0t4s83fn9j3gbbsed6aovv9qpojqos@import.calendar.google.com
      text: "ISI"
      color: "#1088ff"
      public:
        html: "https://www.google.com/calendar/embed?src=au0t4s83fn9j3gbbsed6aovv9qpojqos%40import.calendar.google.com&ctz=Europe/Paris"
        ical: "https://www.google.com/calendar/ical/au0t4s83fn9j3gbbsed6aovv9qpojqos%40import.calendar.google.com/public/basic.ics"
    evtsBDE: 
      id: lhonilnm3lvk7o4g1d556pf1hk@group.calendar.google.com
      text: "Évènements"
      color: "#9a0041"
      public:
        html: "https://calendar.google.com/calendar/embed?src=lhonilnm3lvk7o4g1d556pf1hk%40group.calendar.google.com&ctz=Europe/Brussels"
        ical: "https://calendar.google.com/calendar/ical/lhonilnm3lvk7o4g1d556pf1hk%40group.calendar.google.com/public/basic.ics"
    campagne:
      id: kf3uhrlgbin1aae9uvvii1m6bc@group.calendar.google.com
      text: "Campagne"
      color: "#390060"
      public:
        html: "https://calendar.google.com/calendar/embed?src=kf3uhrlgbin1aae9uvvii1m6bc%40group.calendar.google.com&ctz=Europe/Paris"
        ical: "https://calendar.google.com/calendar/ical/kf3uhrlgbin1aae9uvvii1m6bc%40group.calendar.google.com/public/basic.ics"
aws:
  access_key_id: AKIAIPVH6UOBL23IZXBA
  secret_access_key: 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
  bucket: ares-intranet-storage
  bucket-profiles: "ares-intranet-profiles"
